export const news = [
  {
    id: 1,
    image:
      "https://www.portoglobalhub.ipp.pt/reconhecidos-especialistas-discutem-o-impacto-da-industria-4-0-no-mercado-de-trabalho/image_preview",
    title: "Reconhecidos especialistas discutem o impacto da indústria 4.0",
    desc:
      "A 10 de Fevereiro de 2021, o projecto HubIT irá organizar a conferência virtual “LABOURTECH 2021 - Industry 4.0 technologies and its impact on the labour market” em colaboração com o P.PORTO.",
    date: "05 de março",
    content:
      "O objectivo do evento é discutir e compreender o impacto das tecnologias do futuro no mercado de trabalho, com especial atenção ao papel da inovação e às perspetivas das organizações, dos empregados e da sociedade. Technological advances can bring many benefits for our society with significant impact in the way we communicate, work and live. These advances had led us to the fourth industrial revolution or Industry 4.0, where technologies, such as large-scale machine-to-machine communication (M2M), the internet of things (IoT), artificial intelligence (AI) and automation have disrupted the labour market, making us more efficient, more productive and more cost-efficient. But, would these advances make us more dispensable? Would they increase the control over employees’ performance? How will they affect the decision-making process of an organisation? Os avanços tecnológicos podem trazer muitos benefícios para a sociedade com um impacto significativo na forma como comunicamos, trabalhamos e vivemos. Estes avanços levaram-nos à quarta revolução industrial ou Indústria 4.0, onde tecnologias como a comunicação em grande escala, a Internet das coisas (IoT) e a inteligência artificial (IA) alteraram o mercado de trabalho, tornando-nos mais eficientes, mais produtivos e mais rentáveis. Mas, será que estes avanços tornam os trabalhadores mais dispensáveis? Aumentariam eles o controlo sobre o desempenho dos empregados? Como irão afetar o processo de tomada de decisão de uma organização? A conferência LABOURTECH 2021, aborda os impactos positivos e negativos das tecnologias do futuro no mercado de trabalho e o papel da inovação na Indústria 4.0. Além do mais serão apresentados os resultados adquiridos durante os 30 meses de execução do projeto HubIT. A conferência LABOURTECH 2021 irá juntar reconhecidos especialistas das mais diversas áreas de atuação. Qualquer pessoa pode participar com uma inscrição online aqui (gratuita). Os participantes terão a oportunidade de fazer perguntas durante a sessão e até mesmo de trabalhar em rede com outros participantes."
  },
  {
    id: 2,
    image:
      "https://www.portoglobalhub.ipp.pt/programa-portugal-tourism-minds-fecha-a-sua-1a-edicao/image_preview",
    title: "Programa Portugal Tourism Minds fecha a sua 1ª edição",
    desc:
      "O Demo Day Virtual do programa Portugal Tourism Minds ocorreu no passado dia 29 de Outubro e contou com mais de 50 participantes de diversos setores do turismo em Portugal.",
    date: "05 de março",
    content:
      "O programa de aceleração Portugal Tourism Minds, promovido pela Startup Porto em parceria com o Turismo de Portugal, AHRESP, Turismo Porto e Norte de Portugal e Escola Superior de Hotelaria e Turismo do Porto, chegou ao fim da sua 1ª edição no passado dia 29 de Outubro com a apresentação dos empreendedores no evento Demo Day Virtual. Face à situação pandémica que assola o mundo inteiro, o evento teve lugar através de uma plataforma digital, contudo de nada desmoralizou a participação no Demo Day Virtual. Este contou com mais de 50 participantes de diversos setores do turismo, desde representantes do turismo de freguesias e concelhos do país, agentes de viagens, professores, investidores público e privados e empreendedores em busca de uma melhor resposta para a difícil situação que o turismo enfrenta. O Demo Day Virtual contou com uma apresentação Pitch das seguintes equipas participante no programa Portugal Tourism Minds: BestRide App, Personal2travel, Move4you, MakeitDouble e Saffe Payments. Para além dos pitch dos empreendedores, houve lugar a uma pequena apresentação por parte do Turismo de Portugal e da Portugal Ventures. No âmbito do programa Portugal Tourism Minds, a Startup Porto atribuiu um prémio MVP, para a melhor ideia, no valor de 2000€ à equipa BestRide App. A atribuição do prémio ficou a cargo de um júri constituído por elementos da Porto Global Hub, Turismo de Portugal e Portugal Ventures. O programa Portugal Tourism Minds foi criada para responder a desafios relacionados com o desenvolvimento sustentável do ecossistema de turismo em Portugal. Durante 4 meses os empreendedores contaram com apoio de especialistas das mais diversas áreas, de forma a sustentar um crescimento saudável da sua ideia/startup."
  },
  {
    id: 3,
    image:
      "https://www.portoglobalhub.ipp.pt/p-porto-realizou-mais-de-6500-testes-a-covid-19/image_preview",
    title: "P.PORTO realizou mais de 6500 testes à COVID-19",
    desc:
      "Com capacidade para realizar até 300 rastreios por dia, o Politécnico do Porto continua a contribuir para o aumento da capacidade de resposta no combate ao SARS-CoV-2",
    date: "05 de março",
    content:
      "Desde fins de maio que o laboratório licenciado de Análises Clínicas do P.PORTO já realizou 6500 testes à COVID-19, um número que cresceu significativamente a partir do momento em que se iniciou a colaboração do Politécnico do Porto com a Administração Regional de Saúde do Norte (ARS-Norte). No âmbito dessa cooperação foram realizados, desde outubro, 4600 testes protocolados à COVID-19. Os testes podem ser realizados no laboratório alocado no Porto Research, Technology & Innovation Center (PORTIC) do Politécnico do Porto, por indicação da ARS-Norte e do médico de família, ou recolhidas nas Áreas dedicadas a Doença Respiratória (ADR) dos Centros de Saúde, nas Áreas dedicadas à COVID-19 (ADC), e entregues no P.PORTO. “A partir do momento em que o laboratório molecular do Politécnico do Porto recebeu parecer favorável do Instituto Nacional de Saúde Doutor Ricardo Jorge | INSA para o diagnóstico SARS-CoV-2 integrado na Rede Nacional de Diagnóstico da COVID-19, fomos contatados, quase de imediato, pela ARS-Norte para apoiar os Centros de Saúde', explica Rúben Fernandes, investigador do PORTIC e coordenador do laboratório. 'De momento' - refere o investigador - ' abrangemos uma área regional que vai do Porto ocidental, zona de Aveiro Norte, São João da Madeira, Santa Maria da Feira, Vale de Cambra e Oliveira de Azeméis, apesar de já termos recebido e recolhido testes mais a sul.” A equipa é composta por 22 profissionais, entre investigadores, médicos e estudantes de licenciatura, mestrado e doutoramento da Escola Superior de Saúde do Politécnico do Porto que trabalham em regime de rotatividade, com turnos de seis horas. Há também uma equipa que faz deslocações, garantindo apoio a zonas fora da área de abrangência, tais como Setúbal ou Coimbra. Para além dos testes protocolados, 'estão a ser realizados testes à comunidade do Politécnico do Porto, a estudantes, à totalidade de estudantes Erasmus, a funcionários, docentes e ocasionalmente a familiares', garante Rúben Fernandes, sublinhando existir também serviços ao exterior a empresas e outros particulares. Num contexto severo de evolução significativa do número de casos, o investigador avalia uma percentagem diária de 30% de casos positivos, apesar de existir variáveis e oscilações. Recordamos que a região norte continua a ser a que regista mais casos e óbitos, com 2.284 novos casos e 50 óbitos só nas últimas 24 horas (dados de 24 de novembro). 'As medidas individuais continuam a ser a forma mais eficaz de ultrapassar este desafio, declara ainda em jeito de conclusão, só nós podemos colocar um travão a esta pandemia, respeitando as medidas de distanciamento social e as medidas individuais de higienização. Esta é a chave para parar esta pandemia.'"
  }
];
